#!/bin/bash
username=$(id -u -n 1000)
# Configure bash to use nala wrapper instead of apt
usenala="/home/$username/.use-nala"
rusenala="/root/.use-nala"
uzshrc="/home/$username/.zshrc"
rbashrc="/root/.bashrc"
if [ ! -f "$usenala" ]; then
cat << \EOF > "$usenala"
apt() {
  command nala "$@"
}
sudo() {
  if [ "$1" = "apt" ]; then
    shift
    command sudo nala "$@"
  else
    command sudo "$@"
  fi
}
EOF
cat << EOF >> "$uzshrc"
if [ -f "$usenala" ]; then
        . "$usenala"
fi
EOF
fi

if [ ! -f "$rbashrc" ]; then
cat << \EOF > "$rbashrc"
apt() {
  command nala "$@"
}
EOF
cat << EOF >> "$rbashrc"
if [ -f "$rbashrc" ]; then
        . "$rbashrc"
fi
EOF
fi
